spring.application.name=Online-Examination-Project
spring.datasource.url=jdbc:mysql://localhost:3306/examinationproject
spring.datasource.username=root
spring.datasource.password=Tejas@98971
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true